### ISSUE TITLE
Vortex Issue in -pwnology-'s TM farming macros

### ISSUE THREAD

**Issue by kastyr1984** [MacroTeam/FFBE-Macros#1]
A bunch of comments on this issue here: https://www.reddit.com/r/FFBraveExvius/comments/62ylyr/vortex_flaw_in_pwnology_ultimate_macro_script/?st=j1427fjm&sh=3eb95bd0

The salient point seems to be outlined in the quote below:

> The touch point that needs to be changed is 735:350 and/or the AUTO press needs to be removed and changed to tap unit 2 as a failsafe instead, that way if you end up in the wrong content, all your units wont attack, causing it too pause and prevent further damage.
>
> Maybe someone with experience with Nox scripts can fix it and post an update. This can potentially wipe your nrg and lapis if not fixed immediately.

**Comment by kastyr1984** [comment]
Mcgillby says:

> Change all the 735:350 to 780:259 and it should be fixed

I believe this refers to the point 727:355, and I'll be making the change to the code in another branch for testing purposes.

**Comment by Mcgillby** [comment]
735:350 is in the MEmu version. for some reason the scripts on pwnologys page are not uniform?? and it doesnt work on 2.9.6 memu. ive fixed the NOX . there was 434 clicks over vortex (10% chance if hit homescreen).  370|735  to 259|780 ive also removed the auto press at 77|1222 and changed it to 345|1035 on line 2423. it seems to miss the new mysidia content but i dont know what all tha crap is at the end sequence. some kind of reconnection gig? looks like it was left over from the 1.0.0 build to me.

**Comment by kastyr1984** [comment]
We can use the conversion tool to make them uniform in the code base. It's easy for me to do once we identify actual preferred versions.

**Comment by kastyr1984** [comment]
I'm headed home. I'll look at putting in a pull request with this stuff as soon as I'm home.

**Comment by kastyr1984** [comment]
I took Mcgillby's suggestion to change the Auto press. He moved from Nox 370:735 to Nox 259:780. We moved from Nox 370|735 to Nox 461|780. In MEmu that's 735:350 to 780:461 for his change and 735:350 to 780:279 for our change. That's a pretty big difference. Can somebody shine a light on the differences there so we can pick a final version?

**Comment by Mcgillby** [comment]
after further review it seems we can remove 780:461 as well as 786:221?? (guess) the remaining press under vortex, I think you guys have it hitting daily mission request. if you use my preposed numbers it will cover the Connection button that 780:461 covers as well as the daily mission bypass, Ive tested your version working in its current state, but if we are going forward with one design, my script has already address these things. You could remove 3 touch points from the sequence and move them too the bottom part of the screen (where all the action is).

**Comment by Mcgillby** [comment]
your suggested changes are on the bottom right of [THIS](http://i.imgur.com/S4nae9E.jpg) button, mine is on the bottom left side. My proposed change also covers daily mission bypass, therefore is prefered.

**Comment by Mcgillby** [comment]
On a side note, finally hit 900+ATK 916ATK with Orlandu :+1:

**Comment by Mcgillby** [comment]
i found another bug, there is a sequence at the end that hits all the corners of the screen, this will lead into a dungeon in the new mysidia content, it seems very arbitrary, why is it there?

**Comment by Mcgillby** [comment]
i found another issue, your proposed touch point covers the GO button on the daily mission screen, I got stuck. im making a video now,    

 https://vid.me/Ek31

**Comment by kastyr1984** [comment]
Nobody knows what you're talking about with the corners without line numbers or code snippets. Even then I might not know without hearing from the original authors but maybe we could safely remove anyway.. Maybe that's the right question to ask. Also, is this introduced by my coordinate plan or just happens to be in the original code? I still can't get you to confirm your Memu resolution settings, btw.

**Comment by Mcgillby** [comment]
This is the new coordinate proposed

**Comment by kastyr1984** [comment]
So the corners presses are caused by my changed coordinate?

**Comment by Mcgillby** [comment]
im not looking at the code, im looking at the touch pattern, after running the cycle, there is a press at the upper left upper right then bottom left.

**Comment by Mcgillby** [comment]
no no https://vid.me/Ek31 is caused by the new co-ordinates. The corner thing is in the original code.

**Comment by Mcgillby** [comment]
wrong video i think... one sec.

**Comment by kastyr1984** [comment]
Can you identify where in the script these corner presses occur? Maybe we can cut them out and test as another revision.

**Comment by Mcgillby** [comment]
https://vid.me/wC28 still processing wth

**Comment by Mcgillby** [comment]
yes, its at the very end. run it to do one loop, you will see it at the end.. look for coordinates that are close to the minimum/maximum

**Comment by kastyr1984** [comment]
I'm off to bed again. Maybe I'll look for these in the morning.

I also want to see if biri got the same daily mission problem because it didn't effect my tests at all.

And please confirm your Memu resolution settings for me.

**Comment by ghost** [comment]
Just tested this, no problem with dailies for me, using standard 1280x720 res

**Comment by kastyr1984** [comment]
Closing issue for now as an acceptable fix with input from all sides has been implemented.

**Comment by Mcgillby** [comment]
https://vid.me/H0WO

**Comment by Mcgillby** [comment]
that clearly shows placement over [GO] button, will cause it too break unexpectedly, not a saftey issue tho.

**Comment by kastyr1984** [comment]
As mentioned before, I think this is because you're not using the default MEmu device resolution settings, so you don't have your y coordinates mapped on an inverse plane. Zero issues after a good deal of testing from me and @birbussi so we should be good to go.

**Comment by Mcgillby** [comment]
no, i placed a hotkey over the spot it was hittting.

**Comment by Mcgillby** [comment]
its all to do with placement, i didnt go thru the code, I placed a hot key over the exact spot it was hitting, thats how i can test for different scenarios.

**Comment by Mcgillby** [comment]
there is maybe 20% chance of hitting GO button if daily mission screen comes up, which is once per day.

**Comment by Mcgillby** [comment]
Not a saftey issue ttho, but it will cause breakage.

**Comment by kastyr1984** [comment]
I understand. Hell, I can edit the key placement files directly. But your coordinates will detect differently on the y-plane if you have a non-standard MEmu resolution setup. I don't think you're listening to what I'm saying at all.

**Comment by Mcgillby** [comment]
I know what your saying. I tested it in NOX, you know how you can see the mouse cursors? I turned on hotkeys and lined it up directly with where its hitting.

**Comment by Mcgillby** [comment]
you can go with it if you want, but I ensure you it exists

**Comment by kastyr1984** [comment]
What are the specific coordinate values you're worried about?

**Comment by Mcgillby** [comment]
https://vid.me/DKwK

**Comment by Mcgillby** [comment]
the new one you enetered for the fix, ill find them

**Comment by Mcgillby** [comment]
one of the two atthe end of the video, i believe its the lower of the two

**Comment by Mcgillby** [comment]
461|780

**Comment by kastyr1984** [comment]
Let's move discussion to ticket #9. I went ahead and reopened it.
