### ISSUE TITLE
Inversion still exists on [480] [NOX] NR and NR+TIMER scripts

### ISSUE THREAD

**Issue by Mcgillby** [MacroTeam/FFBE-Macros#15]

**Comment by Mcgillby** [comment]
https://github.com/kastyr1984/FFBE-Macros/blob/mcgillbymini/Mcgillby/Nox/no_refills_%5B480%5D_%5Bmemu%5D.txt

**Comment by Mcgillby** [comment]
https://github.com/kastyr1984/FFBE-Macros/blob/mcgillbymini/Mcgillby/Nox/no_refills_%2B_timer_%5B480%5D_%5Bmemu%5D.txt

**Comment by Mcgillby** [comment]
TM refill 480 working perfectly

**Comment by Mcgillby** [comment]
Also exists all NOX versions except TM Refill 720 and 480, Havent tested hiro

**Comment by kastyr1984** [comment]
Merged new changes in at: https://github.com/kastyr1984/FFBE-Macros/tree/mcgillbymini

Please test when you can

**Comment by Mcgillby** [comment]
thanks, just got home form work, testing now, ill slow down on the comments, sorry, i didnt realize it was linked to  your email :\

**Comment by Mcgillby** [comment]
Okay so I have tested 480 NO Refill+Timer , It working correctly, Id like to make adjustments to the timings of the click release. I can use a text editor and change all 01000 to 10000 in the timing, it seems to work better, but Id like to make the changes here so we can compare them, how do I do that, or should I just do it and send you the updated file? EDIT: SORRY LOOKING AT MEmu SCRIPT, I think in nox, it would be 01 to 10. Seems to be working good.

**Comment by Mcgillby** [comment]
Question for you, If I was able to get phone resolutions for HIRO like 1080x1920 or 1440x2560 would it run on peoples smartphones? The reason I asked is because I tryed it on my samsung galxy and it had no functionality.

**Comment by kastyr1984** [comment]
Yeah. We can either convert with tool or rely on Hiro to do conversion
automatically. I'll also teach you how to do branchs and pull requests
later.

**Comment by Mcgillby** [comment]
K thanks, Ive tested all the 480 resolutions, everything looks good.

**Comment by Mcgillby** [comment]
Sorry Im not seeing NOX 720 No Refill & NR + Timer, Just HIRO. Im in the minitree.

EDIT: NVM FOUND THEM

**Comment by Mcgillby** [comment]
Okay I ran into a major problem with the converted MEmu to NOx 720 script. The touches are hitting slightly right and up of where they are supposed to be, the code is right, what is happening? Im adjusting the numbers to hit the buttons, im completly missing the friend request deny, I have to run some more tests, you have any idea why its doing this?

**Comment by Mcgillby** [comment]
https://github.com/kastyr1984/FFBE-Macros/blob/mcgillbymini/Mcgillby/Nox/tm_refills_720.txt

you able to try this and see if it misses the friend request deny for you ? the numbers are right but for some reason its missing, every other button is working tho.

**Comment by Mcgillby** [comment]
I fixed it. I think I did the pull request thing right

**Comment by Mcgillby** [comment]
maybe you or @biribussi  can test it?

**Comment by kastyr1984** [comment]
I went ahead and merged your changes. I'd test but it's late and I've been running around all day and I'm totally zonked. Problem should be fixed with #17 so I'm closing this issue for now.
