### ISSUE TITLE
Exploration Automation

### ISSUE THREAD

**Issue by Kawoxux** [MacroTeam/FFBE-Macros#18]
Hi Guys,
I think it's worth having set scripts for explorations that can be used to rapidly build continuous exploration scripts.
There will naturally be an earnest to having these completed as quick as possible when new content is released, so not having to faff with setting up menu selections etc will be key.
It will also mean people can make their own scripts if we're tied up/can't get to it for a few days + will encourage community members to also contribute

We need to have something like the following:
1. Stage Selection -> sprite appear on Map - Variants for Nox/Memu/FRep etc
2. Clear all battles (Wiggle script to auto battle clear battles - would also be good to see if we can work out an approximate time per battle - so as explorations change we know what with say 40s per battle, the clear battles script needs to run for 10 mins (15battles x 40 seconds = 600 Secs/10 mins). This way if feedback suggests that there's an aimless 2 min run, or not enough time to clear all battles, we can manually add in an additional step rapidly without having to redo the entire script.
3. Boss Fight Automation - from when you click to enter boss fight (pressing auto numerous times to ensure that auto battle has/hasn't been unselected - say 1 minute).
4. Leave Exploration button ->exploration results->Clear Daily Result - to finish on Stage Selection screen again.

Then we can manually enter in 2 stages between steps 2 and 3:
A: Return sprite to neutral location -> Area 2 Battles location
~Step 2 for Auto-Battles is repeated here
B: Return Sprite to Neutral Location -> Gathering points->boss Enter Menu

**Comment by kastyr1984** [comment]
This sounds great. I'm on board and can definitely help with merging the macros and building some of them. I'll defer largely to others with more experience in the nuts and bolts of it, but if you want to start parceling out the work you can count me in. I'm also big on the hand editing and reduction of scripts so I think I can be a big help there.

**Comment by Kawoxux** [comment]
Cheers K.
I've been working on one for Magic Library today. Unfortunately got sidetracked at work so it's not 100% yet, but i'll try and spend a bit of time over the weekend to get it to the finished product.
Will also split up the more common aspects. - at present i just use Pwnology's area clear for step 2. - if there's a new variant of that which you guys have been working on let me know.

**Comment by kastyr1984** [comment]
If we can throw this into a branch split up into its components (I can provide a merged script build from components automatically), I'd be interested to help development and performance. We can maintain the level specific elements in there as well, since we can fine tune those pieces as well, while being more enabled to carry over the area-specific elements. We just have to be careful how splitting is done because we need to 0-base the time of each segment or it will merge with long pauses.

**Comment by Kawoxux** [comment]
Yeah i've already branched off my own folder from the main. have populated with readme's etc to split up and define areas.

the initial testing can be performed independently with a full run that can be compiled - then it's just a matter of pushing through to the end of part 1 - removing the delay line, rinse & repeat

**Comment by kastyr1984** [comment]
Just so I understand :

1. Go to exploration from main screen and launch
2. Move to area 1 if needed, getting mat drops
3. Wiggle and fight.
4. Move to known position along wiggle and fight movement plot
5. Move to area 2, getting mat drops from area 1
6. Wiggle and fight
7. Move to boss, getting mat drops from area 2
8. Boss battle
9. Move to exit, getting mat drops if needed
10. Go through finish screen and reset to main screen using back button

**Comment by Kawoxux** [comment]
Almost, ultimately it would look like this:

1. Start Script at Stage Select screen - Takes through companion select and Start Stage button
2. Wriggle and fight - clearing all mobs in Area 1.
3. Navigate to known safe position hitting 2x walls to ensure remainder of script operates. Then move sprite to area 2. Collecting Collection Points if relevant to exploration.
4. Wriggle and fight - clearing all mobs in Area 2.
5. Navigate to known safe position hitting 2x walls to ensure remainder of script operates in Area 2. Then collecting remaining Collection Points + Navigating to Boss Fight.
6. Boss battle including clicking the start fight button - needs multiple auto button presses 3s apart.
7. Click Continue, Collect remaining drop points and navigate to exit
8. Go through finish screen and reset to main screen using back button

Points 3, 5, 7 will be unique PER exploration - remaining points can be set in stone.

**Comment by Mcgillby** [comment]
You gotta Wriggle and clear first, @Kawoxux  has got it exactly the way ive been theorizing it. But when you rnavigating, you can run straight into some walls to be able to repostion properly, heres a video example.

https://vid.me/HKSO

notice how when there is a wall infront, i just run straight into it, like im trying to walk thru the wall, then reposition, that way if there is some lag, a missed step wont be catastrophic. When I tryed it without the extra steps into the walls, it would get lost. This was my first attempt at an exploration, not sure if that is even the best method.

**Comment by kastyr1984** [comment]
Sometimes you gotta walk first. Dwarves Forge doesn't have enemies in the first area. You grab materials and move to "area 1" then wriggle and clear.

**Comment by Mcgillby** [comment]
A exploration like Dwarves forge is unique? Or is there another example like that, im only at Zoldaad Castle.

**Comment by Mcgillby** [comment]
Going from step 2 to 3 is the most difficult part to pull off imo, because the position after the wriggle is not going to be the same everytime. Especially where you start off in an open area. Are these Exploration Builds supposed to play the exploration 1x thru, or play on a continuous loop.

**Comment by kastyr1984** [comment]
If you have proper placement in the wriggle and fight then you're going to be along a set number of possibilities. The trick is to 
a. place yourself in somewhere you can wriggle appropriately without moving from a set of possibilities
b. move to a terminal point along the set number of possibilities and then complete moving through the exploration like that

For example if you're on a diagonal wiggle in a known spot from the entrance of the level, continue to move back and forth until the amount of time it would take to exhaust the number of fights in that area is complete. Then perform a set of moves that will place you at the top or bottom of that diagonal from any spot you could possibly be on it. Then begin the rest of your moves from there.

**Comment by kastyr1984** [comment]
Dwarves Forge might be unique for now in having a no-combat entry area that also requires navigation to find materials, but I don't think it will present an issue to assume that others may have similar characteristics in the future.

Also, working off diagonals rather than working off of hitting 2x walls will likely serve better in an exploration like mystic woods where the weird maze maps might not actually allow you to find an interior right angled wall in Area 2.

**Comment by kastyr1984** [comment]
@Kawoxux, can you explain the need for the structure of boss fight handling?

**Comment by Kawoxux** [comment]
Sorry guys not at home this weekend.

I'm aware of the pre -emptive steps to navigate into a particular corner. I've been working on a script for magic library today which has a table to navigate around. There's numerous places for it to get stuck. So after area one clear, you then have about 20 seconds of clicks to get rain back into an ideal location using the walls to bring him to the desired point.

Re boss structure handling it basically just involves hitting auto, but if you have continuous auto battle on and it clicks auto then you actually stop fighting (because click turns auto off) continually pressing auto button ensures it will finish the battle.

It won't travel any further because you get the continue/leave buttons that need to be clicked before anything else can happen

Sent from my Sony Xperia™ smartphone

---- kastyr wrote ----


@Kawoxux<https://github.com/Kawoxux>, can you explain the need for the structure of boss fight handling?

**Comment by kastyr1984** [comment]
I just put in a merge script. It will require modification, namely we'll need to give it a certain number of repeating merges on the wiggle scripts, but it theoretically should be worth a test.

**Comment by kastyr1984** [comment]
This is now a point of very active development on our part, so I'm closing the issue.
