### ISSUE TITLE
Adjusting TM Refills Script to JP

### ISSUE THREAD

**Issue by Mcgillby** [MacroTeam/FFBE-Macros#20]
Request for a JP script, would like to add it to my page.

>Yo man, so your GL TM with Refills script is killing it. Best macro I have used so far.
It is almost usable on JP but there is an additional window that needs to be dealt with occasionally when a companion unit has a gear change.

Waiting for screenshots

**Comment by Mcgillby** [comment]
I think I got it. It was exactly what I thought it was. The click was just outside the bottom left corner of the button. I didnt get the exact screenshot, but im assuming it is the same as the connection screen like it is in GL. I moved the co-ordinates up and right to cover the button. Fixed the issue. both me and commenter are going to test overnight for errors. Ill upload the script to my tree.

**Comment by Mcgillby** [comment]
How do I upload files into my branch?

**Comment by Kawoxux** [comment]
Should be able to just navigate to folder you want then click new file. Can also add a /folder/file name if you have storage ocd like me :)


Sent from my Sony Xperia™ smartphone

---- Mcgillby wrote ----


How do I upload files into my branch?

**Comment by Mcgillby** [comment]
I deleted the current files (names were conflicting) and uploaded all my master scripts in Folders by type and resolution. Should be easier to navigate my files now. I think im finished. Just running each script thru testing. One resolution each day. So far so good.

**Comment by Mcgillby** [comment]
All scripts adapted to JP ver 2.7.0 in latest pull request
