### ISSUE TITLE
Lapis revive units

### ISSUE THREAD

**Issue by kastyr1984** [MacroTeam/FFBE-Macros#3]
The pwnology TM farming scripts will auto revive with lapis according to Mcgillby's comment here: https://www.reddit.com/r/FFBraveExvius/comments/62x2vg/custom_tm_farming_scripts_for_memu/dfu6kkx/

We should confirm the bug and see what can be done to fix.

**Comment by ghost** [comment]
It shouldn't be too hard to confirm the bug, i'll go to a hard dungeon and let the original tm macro script run, give me 5 minutes

**Comment by kastyr1984** [comment]
Cool, thanks. And if you manage to identify the coordinates causing the issue, well, that's bonus points!

Then we're also going to have to figure out what event those coordinates are meant to be there for. There's a lot of eventualities that pwnology and Kitthix are accounting for (which is half the reason it's so worthwhile to be fixing their scripts).

**Comment by ghost** [comment]
Bug confirmed, just used 100 lapis to revive units in mission. I think the click is the one supposed to say YES when you want to refill lapis, but for the coordinates... i don't think i can help you here. Here's a [screenshoot](http://imgur.com/a/ktjyN) i've taken of the reviving screen. the button pressed in the screenshoot are the ones normally cycled, when the script try to refill lapis once in a couple of runs, it hits the YES button. Technically, if we can avoid the click that presses the AUTO button we would be good, because having the units 1 and 3 to attack, the others will remain idle, not ending your turn and actually "pausing" the battle

**Comment by kastyr1984** [comment]
Any chance you can you give me a screenshot of the lapis refill screen so I can overlay them?

**Comment by ghost** [comment]
here it is [screenshoot](http://imgur.com/a/T9Yr0)

**Comment by kastyr1984** [comment]
Is there another screen after you hit 'Use Lapis'?

**Comment by ghost** [comment]
i'll make one right away, but i don't have any lapis right now on memu

**Comment by ghost** [comment]
You're right, i forgot there was another confirmation screen, [here it is](http://imgur.com/a/XuBGa)

Seems to me that the USE LAPIS for refilling and the YES from reviving are pretty much in the same position, probably that's click causing the issue. I noted that reviving units does not have a second confirmation screen like the refill one

**Comment by ghost** [comment]
Well i'm off to bed for now Kas, it's 2 am in the morning here :) i'll leave the fixed macro run all night and see if i get some strange behaviour in the morning. I'll get back to you asap for everything that i'll read here. We should decide something for the other situation, too. later!

**Comment by kastyr1984** [comment]
Thanks for all the help!

**Comment by ghost** [comment]
Ah no problem, i'm here to help!, anyway, i've noted a strange thing. the tm macro, every 4 or 5 cycles (when he's trying to refill lapis, basically), hits the AUTO button, which is probably the source of a good chunk of our problems. I've digged a little in the old thread and i've found [this ](https://www.reddit.com/r/FFBraveExvius/comments/55f44k/lets_talk_nox_macros/dez0l0p/)

Maybe we should just remove it? it's been causing only troubles in the last couple of days. And now, goodnight for real :)

**Comment by kastyr1984** [comment]
That's the kicker, is that I know why Pwnology put it there and I'm trying to think of a truly viable alternative that deals with the issue he was fixing without introducing another issue altogether.

**Comment by ghost** [comment]
But I don't understand, what's the problem if 2 characters attacks the same monster? It will not mess up the macro since it's modular, the monsters usually dies with one hit.

**Comment by kastyr1984** [comment]
The problem occurs when there are two monsters and what is called a race condition occurs. A race condition means the second unit is set to attack before the first unit has registered as attacking and killing the monster, meaning both attack the same monster and then without an "AUTO" click or some other means of fixing the problem, the units just stand there infinitely staring down the second monster.

**Comment by ghost** [comment]
Hm, I was not aware of this problem honestly, now the auto click make sense. What if we sightly delay the two units attack clicks? This will slow down farming a bit, but it can be an acceptable compromise if the alternative is a potential loss of lapis

**Comment by kastyr1984** [comment]
What if people just turned off Continuous Auto Battle? The issue could still exist but would be so much less potentially devastating.

**Comment by ghost** [comment]
Could work, but in my test run before, the tm party was wiped in a single encounter. Given the frequency of the auto button getting pressed, we would still have a lot of problems

**Comment by kastyr1984** [comment]
Mcgillby solved this by eliminating the auto press and replacing it with
another unit attacking. Might be the best idea. I just wish there were a
good way to fix a crash to the main screen, which is what puts us in this
shitty situation in the first place.

**Comment by Mcgillby** [comment]
hey guys mcgillby here. ive fixed all the issues with the script. as soon as that script gets fixed or replaced I will be nice. I really take this shit seriously. im sorry about freaking out but this should have been fixed a long time ago. anyways ive fixed the script and patched the errors. i still feel like we should work together and make  a single combined effort. i dont mind going at it myself either. anyways here it is

https://pastebin.com/d12VadNc

**Comment by Mcgillby** [comment]
biribussi, I appriciate that your using your lapis and testing it, it shows me that you take this seriously. You can clearly see how dangerous this build can be (I still handled it wrong I know) and I couldnt be more happy to see you guys taking the steps to fix it.

**Comment by Mcgillby** [comment]
>You're right, i forgot there was another confirmation screen, [here it is](http://imgur.com/a/XuBGa) 
>
>Seems to me that the USE LAPIS for refilling and the YES from reviving are pretty much in the same position, probably that's click causing the issue. I noted that reviving units does not have a second confirmation screen like the refill one

your picture of the confirmation screen has the toolbar included, when using screenshots for overlay purposes, you need to take them in the exact screen ratio your using  [HERE](http://i.imgur.com/MGRmVBa.png) The button placement is slightly higher then the screenshot given by biribussi

Do you guys know if there are seperate presses for Lapis refill and confirmation, because you only need one spot to cover both, and it is below revive. I bet you the first click for refresh, Is the Dirty one.

**Comment by Mcgillby** [comment]
a suggestion for further testing is too start a new account, you can do the story for about an hour and have 5000 lapis. and you get too watch the refresh happen every 20 runs. when you run out of easily farmable lapis, throw it away and start a new account.

**Comment by kastyr1984** [comment]
I'm gonna go out on a line and say that biri didn't mind spending his 100 lapis for the cause but now that you mention it I might send a donation his way to cover some testing costs. Good idea. Back to bed now!

**Comment by Mcgillby** [comment]
if we still have a button press over revive, there is still a miniscule chance that someone will start it with continuous auto battle on in the wrong content ( its happened to me before, starting in the wrong content, not auto-battle I never lost any lapis, just a night of farming) if the button press for revive happens, it will continue until 0 lapis, it needs to be fixed. you want to move it to hit the top of the confirmation button, but still miss the espers on the depart screen. This is low enough to miss the revive and combine both Lapis Refill and Confirmation to the same touch point, you can spread them out a bit too prevent going into es-exit

**Comment by Mcgillby** [comment]
goodnight, i got the day off work tomorrow so im going to do some more testing

**Comment by ghost** [comment]
> I just wish there were a
good way to fix a crash to the main screen, which is what puts us in this
shitty situation in the first place.

Crashes are... tricky to work around. I studied them some months ago working with team pwnology, my conclusion at the time was that crashes are a combination of natural emulator instability, poor software optimization and a memory leak caused by the app-emulator system. I've recently found some advanced settings that would allow a better management of the ram menory used by the emulator, maybe we'll find a way to reduce them. I'll look into it
