### ISSUE TITLE
Leaving MACROTEAM

### ISSUE THREAD

**Issue by Mcgillby** [MacroTeam/FFBE-Macros#54]
Hi guys, its been great but Im making my own Repository so if its possible can you please remove my files from this repository? Also u/nazta has asked me to create a macro megathread, too many macro posts going on since Lets Talk NOx page was archived, so he asked me if I can find some volunteers.. your exploration macros will be a good fit, especially since u/-pwnology- deleted the entire Lets Talk Nox Page last night..

**Comment by kastyr1984** [comment]
Sure. Can you please delete your clone of this repository?

**Comment by Mcgillby** [comment]
Is that like my Fork?

**Comment by Mcgillby** [comment]
Okay I think I did it. 

Here is my page if you need to access my files

https://github.com/Mcgillby/Mcgillby-Macros
